CadViewer.iframeTitle=CAD preview: {0}

# SDK sample labels below. Remove when sample types/aspects are deleted.


# Labels for custom types and aspects
# Used in "Manage Aspects" and "Change Type" dialogs
#
type.acme_document=ACME Document
aspect.acme_securityClassified=Security Classified

# View,Edit,Search,Create Form labels for types and aspects
#
form.set.label.acme.document= ACME Document Information
form.field.label.acme.documentId=ACME Document Id
form.field.label.acme.securityClassification=Security Classification

# Advanced Search Form labels (only for types)
#
form.label.advancedsearch.acmeDocument=ACME Documents
form.description.advancedsearch.acmeDocument=Search for any ACME Documents

